### ISSUE TITLE
Type error in toast-region.tsx

### ISSUE THREAD

**Issue by gregmsanderson** [zaichaopan/tailwind-react-aria-components-starter-kits#10]
Hi,

As the image shows, it seems there is a type error.

That _seems_ to be due to the presence of `[...closeButtonProps}` on `<CloseButton />`. Removing that makes it go away. So its type does not match.

I can see the toast-region is based on what RAC is doing on https://react-spectrum.adobe.com/react-aria/useToast.html#typescript Sure enough, it's passing that same `[...closeButtonProps}` prop. I would assume _that_ works because _its_ `<Button />` is based on the useButton hook: https://react-spectrum.adobe.com/react-aria/useToast.html#button Rather than the Button component. Or perhaps its because the Button component has been modified and so its types differ ... ? Hmm.

(I also wonder whether it should be `ToastRegion.tsx` to match the other components?)

![type-error](https://github.com/user-attachments/assets/3258639d-63af-4c91-910f-8a9215ef2ecf)

**Comment by zaichaopan** [comment]
thanks for reporting. The issue is fixed now

**Comment by gregmsanderson** [comment]
Nice. The type fix was more complicated than I thought. Glad I left it to you!
