### ISSUE TITLE
Is there a license for the components?

### ISSUE THREAD

**Issue by gregmsanderson** [zaichaopan/tailwind-react-aria-components-starter-kits#2]
Hello,

I wondered if you could add a license for the components?

For example:

https://github.com/shadcn-ui/ui/blob/main/LICENSE.md

Thanks.

**Comment by zaichaopan** [comment]
@gregmsanderson  I added MIT license. Thanks.

**Comment by gregmsanderson** [comment]
@zaichaopan Great! Thanks.
