### ISSUE TITLE
A focused form input within a group after a failed validation has a duplicated border

### ISSUE THREAD

**Issue by gregmsanderson** [zaichaopan/tailwind-react-aria-components-starter-kits#3]
Hello,

I noticed that if a form input that's within an input group fails a form validation, the red border is duplicated. Both the input group _and_ the input have it. Only the group should.

You can see it in the storybook. If you click submit, the validation fails and only the group has the border. That's correct. But when you focus the input, that gains it too.

https://zaichaopan.github.io/tailwind-react-aria-components-starter-kits/iframe.html?viewMode=docs&id=textfield--docs#with%20validation

![failed-form-validation](https://github.com/zaichaopan/tailwind-react-aria-components-starter-kits/assets/10390169/f886b973-d66c-42c1-b3ae-e956453052d9)

**Comment by zaichaopan-alianza** [comment]
Thanks for reporting. It should be fixed now.  I just made lots of updates today and might introduce more issues. The project is still working in progress and lots of work to make those ui components beauty and simple to use and customize.

**Comment by gregmsanderson** [comment]
No problem, all good. It was just something I noticed.
