### ISSUE TITLE
Possible addition of an underline offset?

### ISSUE THREAD

**Issue by gregmsanderson** [zaichaopan/tailwind-react-aria-components-starter-kits#7]
Hello,

I wonder if you think an offset e.g `underline-offset-4` would be nice to add:

```js
export function TextLink(props: LinkProps) {
  return (
    <Link
      {...props}
      className={composeTailwindRenderProps(props.className, 'underline underline-offset-4')}
    />
  );
}
```

Shadcn and Catalyst both do for their text links since it looks a bit nicer e.g:

![offset](https://github.com/zaichaopan/tailwind-react-aria-components-starter-kits/assets/10390169/741b87b8-50f1-418a-86ea-acd7dbad9054)

I can simply override the class but it seemed a nice addition to the default. I could add a PR if you like.

Thanks.

**Comment by zaichaopan-alianza** [comment]
@gregmsanderson that looks nicer! Please add it! Thanks!

**Comment by gregmsanderson** [comment]
Great!

That's done :)

https://github.com/zaichaopan/tailwind-react-aria-components-starter-kits/pull/8
